# Dockerfile of Apache CloudStack mgmt. server MySQL DB on Ubuntu

FROM ubuntu:16.04

MAINTAINER opsforge.io
LABEL name="cloudstack-mysql"
LABEL version="0.0.1"

CMD /bin/zsh -c '???'

USER root

RUN echo -e "Hello World"
